P.push(["be able to ~","能够…","〜することができる","She is able to swim very fast.","彼女(かのじょ)はとても速(はや)く泳(およ)ぐことができる。",2]);
P.push(["be afraid of ~","害怕…","〜を恐(おそ)れる","I am afraid of big dogs.","私(わたし)は大(おお)きな犬(いぬ)が怖(こわ)い。",2]);
P.push(["be different from ~","与…不同","〜と違(ちが)う","His idea is different from mine.","彼(かれ)の考(かんが)えは私(わたし)のとは違(ちが)う。",2]);
P.push(["be famous for ~","以…闻名","〜で有名(ゆうめい)である","This town is famous for its temples.","この町(まち)は寺(てら)で有名(ゆうめい)だ。",2]);
P.push(["be full of ~","充满…","〜でいっぱいである","The box was full of old books.","その箱(はこ)は古(ふる)い本(ほん)でいっぱいだった。",2]);
P.push(["be good at ~","擅长…","〜が得意(とくい)である","He is good at playing the guitar.","彼(かれ)はギターを弾(ひ)くのが得意(とくい)だ。",3]);
P.push(["be interested in ~","对…感兴趣","〜に興味(きょうみ)がある","I am interested in foreign cultures.","私(わたし)は外国(がいこく)の文化(ぶんか)に興味(きょうみ)がある。",2]);
P.push(["be kind to ~","对…友善","〜に親切(しんせつ)である","She is always kind to everyone.","彼女(かのじょ)はいつもみんなに親切(しんせつ)だ。",3]);
P.push(["be known as ~","作为…而闻名","〜として知(し)られている","He is known as a great artist.","彼(かれ)は偉大(いだい)な芸術家(げいじゅつか)として知(し)られている。",1]);
P.push(["be late for ~","…迟到","〜に遅(おく)れる","Don't be late for school.","学校(がっこう)に遅(おく)れてはいけない。",3]);
P.push(["be made of ~","由…制成","〜でできている","This desk is made of wood.","この机(つくえ)は木(き)でできている。",2]);
P.push(["be made from ~","由…制成〔变质〕","〜から作(つく)られる","Cheese is made from milk.","チーズは牛乳(ぎゅうにゅう)から作(つく)られる。",2]);
P.push(["be proud of ~","为…自豪","〜を誇(ほこ)りに思(おも)う","I am proud of my hometown.","私(わたし)は故郷(こきょう)を誇(ほこ)りに思(おも)う。",1]);
P.push(["be surprised at ~","对…惊讶","〜に驚(おどろ)く","We were surprised at the news.","私(わたし)たちはその知(し)らせに驚(おどろ)いた。",2]);
P.push(["be worried about ~","担心…","〜を心配(しんぱい)している","She is worried about the exam.","彼女(かのじょ)は試験(しけん)を心配(しんぱい)している。",2]);
P.push(["be covered with ~","被…覆盖","〜で覆(おお)われている","The mountain was covered with snow.","その山(やま)は雪(ゆき)で覆(おお)われていた。",1]);
P.push(["be born in ~","出生于…","〜で生(う)まれる","He was born in Osaka.","彼(かれ)は大阪(おおさか)で生(う)まれた。",3]);
P.push(["be filled with ~","充满…","〜で満(み)たされている","Her eyes were filled with tears.","彼女(かのじょ)の目(め)は涙(なみだ)でいっぱいだった。",1]);
P.push(["be based on ~","基于…","〜に基(もと)づいている","This story is based on a real event.","この話(はなし)は実話(じつわ)に基(もと)づいている。",1]);
P.push(["be similar to ~","与…相似","〜に似(に)ている","This word is similar to that one.","この語(ご)はあの語(ご)に似(に)ている。",1]);
P.push(["look at ~","看…","〜を見(み)る","Look at the picture on the wall.","壁(かべ)の絵(え)を見(み)なさい。",3]);
P.push(["look for ~","寻找…","〜を探(さが)す","I am looking for my key.","私(わたし)はかぎを探(さが)している。",3]);
P.push(["look forward to ~","期待…","〜を楽(たの)しみに待(ま)つ","I am looking forward to seeing you.","お会(あ)いするのを楽(たの)しみにしています。",1]);
P.push(["look like ~","看起来像…","〜のように見(み)える","She looks like her mother.","彼女(かのじょ)は母親(ははおや)に似(に)ている。",2]);
P.push(["look up ~","查〔词〕","〔辞書(じしょ)などで〕調(しら)べる","Look up the word in the dictionary.","その語(ご)を辞書(じしょ)で調(しら)べなさい。",2]);
P.push(["take care of ~","照顾…","〜の世話(せわ)をする","I take care of my little brother.","私(わたし)は弟(おとうと)の世話(せわ)をする。",2]);
P.push(["take part in ~","参加…","〜に参加(さんか)する","Many students took part in the event.","多(おお)くの生徒(せいと)がその行事(ぎょうじ)に参加(さんか)した。",1]);
P.push(["take place","举行；发生","行(おこな)われる","The festival takes place in August.","その祭(まつ)りは八月(はちがつ)に行(おこな)われる。",1]);
P.push(["take off ~","脱下；起飞","脱(ぬ)ぐ；離陸(りりく)する","Please take off your shoes here.","ここで靴(くつ)を脱(ぬ)いでください。",2]);
P.push(["take a walk","散步","散歩(さんぽ)する","I take a walk every morning.","私(わたし)は毎朝(まいあさ)散歩(さんぽ)をする。",2]);
P.push(["get up","起床","起(お)きる","I get up at six every day.","私(わたし)は毎日(まいにち)六時(ろくじ)に起(お)きる。",3]);
P.push(["get off ~","下〔车〕","〜を降(お)りる","Get off the bus at the next stop.","次(つぎ)の停留所(ていりゅうじょ)でバスを降(お)りなさい。",2]);
P.push(["get on ~","上〔车〕","〜に乗(の)る","She got on the train at Tokyo.","彼女(かのじょ)は東京(とうきょう)で電車(でんしゃ)に乗(の)った。",2]);
P.push(["get to ~","到达…","〜に着(つ)く","How can I get to the station?","駅(えき)にはどう行(い)けばいいですか。",2]);
P.push(["get along with ~","与…相处融洽","〜と仲良(なかよ)くやる","He gets along with his classmates.","彼(かれ)は同級生(どうきゅうせい)と仲良(なかよ)くやっている。",1]);
P.push(["give up","放弃","あきらめる","Don't give up so easily.","そんなに簡単(かんたん)にあきらめないで。",2]);
P.push(["put on ~","穿上","〜を身(み)につける","Put on your coat. It's cold.","コートを着(き)なさい。寒(さむ)いよ。",2]);
P.push(["turn on ~","打开〔电器〕","〔電気(でんき)などを〕つける","Turn on the light, please.","電気(でんき)をつけてください。",2]);
P.push(["turn off ~","关掉","〔電気(でんき)などを〕消(け)す","Turn off the TV before you go.","出(で)かける前(まえ)にテレビを消(け)しなさい。",2]);
P.push(["come from ~","来自…","〜の出身(しゅっしん)である","She comes from Canada.","彼女(かのじょ)はカナダの出身(しゅっしん)だ。",3]);
P.push(["come true","实现","実現(じつげん)する","My dream came true at last.","私(わたし)の夢(ゆめ)はついに実現(じつげん)した。",2]);
P.push(["go on","继续","続(つづ)く","The meeting went on for two hours.","会議(かいぎ)は二時間(にじかん)続(つづ)いた。",2]);
P.push(["grow up","长大","成長(せいちょう)する","I grew up in a small town.","私(わたし)は小(ちい)さな町(まち)で育(そだ)った。",2]);
P.push(["wake up","醒来","目(め)を覚(さ)ます","I woke up early this morning.","今朝(けさ)は早(はや)く目(め)が覚(さ)めた。",2]);
P.push(["find out ~","查明","〜を見(み)つけ出(だ)す","I found out the truth later.","私(わたし)はあとで真実(しんじつ)を知(し)った。",1]);
P.push(["hurry up","快点","急(いそ)ぐ","Hurry up! We're late.","急(いそ)いで。遅(おく)れるよ。",2]);
P.push(["cheer up","打起精神","元気(げんき)づける","Her words cheered me up.","彼女(かのじょ)の言葉(ことば)は私(わたし)を元気(げんき)づけた。",1]);
P.push(["pick up ~","捡起；接〔人〕","拾(ひろ)う；迎(むか)えに行(い)く","He picked up the trash on the road.","彼(かれ)は道(みち)のごみを拾(ひろ)った。",1]);
P.push(["hand in ~","提交","〜を提出(ていしゅつ)する","Hand in your report by Friday.","金曜日(きんようび)までにレポートを提出(ていしゅつ)しなさい。",1]);
P.push(["carry out ~","执行","〜を実行(じっこう)する","They carried out the plan.","彼(かれ)らはその計画(けいかく)を実行(じっこう)した。",1]);
P.push(["agree with ~","同意…","〜に賛成(さんせい)する","I agree with your opinion.","私(わたし)はあなたの意見(いけん)に賛成(さんせい)だ。",2]);
P.push(["arrive at ~","到达…","〜に到着(とうちゃく)する","We arrived at the hotel at noon.","私(わたし)たちは正午(しょうご)にホテルに到着(とうちゃく)した。",2]);
P.push(["ask for ~","请求…","〜を求(もと)める","He asked for help.","彼(かれ)は助(たす)けを求(もと)めた。",2]);
P.push(["belong to ~","属于…","〜に所属(しょぞく)する","I belong to the science club.","私(わたし)は科学部(かがくぶ)に所属(しょぞく)している。",2]);
P.push(["depend on ~","依靠…","〜次第(しだい)である","It depends on the weather.","それは天気(てんき)次第(しだい)だ。",1]);
P.push(["hear from ~","收到…的消息","〜から便(たよ)りがある","I heard from her last week.","先週(せんしゅう)彼女(かのじょ)から連絡(れんらく)があった。",1]);
P.push(["laugh at ~","嘲笑…","〜を笑(わら)う","Don't laugh at other people's mistakes.","人(ひと)の失敗(しっぱい)を笑(わら)ってはいけない。",1]);
P.push(["listen to ~","听…","〜を聞(き)く","Listen to the CD carefully.","CDを注意深(ちゅういぶか)く聞(き)きなさい。",3]);
P.push(["pay attention to ~","注意…","〜に注意(ちゅうい)を払(はら)う","Pay attention to the signs.","標識(ひょうしき)に注意(ちゅうい)しなさい。",1]);
P.push(["prepare for ~","为…做准备","〜の準備(じゅんび)をする","I am preparing for the exam.","私(わたし)は試験(しけん)の準備(じゅんび)をしている。",2]);
P.push(["think of ~","想到…","〜を思(おも)いつく","I can't think of a good idea.","よい考(かんが)えが思(おも)いつかない。",2]);
P.push(["wait for ~","等待…","〜を待(ま)つ","I waited for the bus for an hour.","私(わたし)は一時間(いちじかん)バスを待(ま)った。",3]);
P.push(["worry about ~","担心…","〜を心配(しんぱい)する","Don't worry about small things.","小(ちい)さなことを心配(しんぱい)しないで。",2]);
P.push(["at first","起初","最初(さいしょ)は","At first I didn't like it.","最初(さいしょ)はそれが好(す)きではなかった。",2]);
P.push(["at last","最终","ついに","At last we finished the work.","ついに私(わたし)たちは仕事(しごと)を終(お)えた。",2]);
P.push(["at once","立刻","すぐに","Come here at once.","すぐにここへ来(き)なさい。",1]);
P.push(["at least","至少","少(すく)なくとも","Sleep at least seven hours.","少(すく)なくとも七時間(ななじかん)は寝(ね)なさい。",1]);
P.push(["at the same time","同时","同時(どうじ)に","They arrived at the same time.","彼(かれ)らは同時(どうじ)に到着(とうちゃく)した。",2]);
P.push(["for a long time","很长时间","長(なが)い間(あいだ)","I have known him for a long time.","私(わたし)は長(なが)い間(あいだ)彼(かれ)を知(し)っている。",2]);
P.push(["for example","例如","たとえば","For example, plastic harms the sea.","たとえば、プラスチックは海(うみ)を害(がい)する。",2]);
P.push(["for the first time","第一次","初(はじ)めて","I saw snow for the first time.","私(わたし)は初(はじ)めて雪(ゆき)を見(み)た。",2]);
P.push(["in fact","事实上","実際(じっさい)には","In fact, the story is true.","実際(じっさい)、その話(はなし)は本当(ほんとう)だ。",1]);
P.push(["in front of ~","在…前面","〜の前(まえ)に","He was standing in front of the door.","彼(かれ)はドアの前(まえ)に立(た)っていた。",2]);
P.push(["in order to ~","为了…","〜するために","She studies hard in order to pass.","彼女(かのじょ)は合格(ごうかく)するために一生懸命(いっしょうけんめい)勉強(べんきょう)する。",1]);
P.push(["in other words","换句话说","言(い)いかえれば","In other words, we must start now.","言(い)いかえれば、今(いま)始(はじ)めなければならない。",1]);
P.push(["in the future","将来","将来(しょうらい)","I want to be a teacher in the future.","将来(しょうらい)、先生(せんせい)になりたい。",2]);
P.push(["on foot","步行","徒歩(とほ)で","I go to school on foot.","私(わたし)は徒歩(とほ)で学校(がっこう)へ行(い)く。",2]);
P.push(["on time","准时","時間(じかん)どおりに","The train came on time.","電車(でんしゃ)は時間(じかん)どおりに来(き)た。",2]);
P.push(["by the way","顺便说","ところで","By the way, how is your family?","ところで、ご家族(かぞく)はお元気(げんき)ですか。",2]);
P.push(["of course","当然","もちろん","Of course, I will help you.","もちろん、お手伝(てつだ)いします。",3]);
P.push(["all over the world","全世界","世界中(せかいじゅう)で","This song is loved all over the world.","この歌(うた)は世界中(せかいじゅう)で愛(あい)されている。",2]);
P.push(["a lot of ~","很多…","たくさんの","There are a lot of books here.","ここにはたくさんの本(ほん)がある。",3]);
P.push(["a few ~","一些…","少(すこ)しの","I have a few questions.","私(わたし)にはいくつか質問(しつもん)がある。",2]);
P.push(["a little","一点","少(すこ)し","I can speak a little English.","私(わたし)は少(すこ)し英語(えいご)が話(はな)せる。",3]);
P.push(["each other","互相","お互(たが)いに","They helped each other.","彼(かれ)らはお互(たが)いに助(たす)け合(あ)った。",2]);
