P.push(["as soon as ~","一…就…","〜するとすぐに","Call me as soon as you arrive.","着(つ)いたらすぐに電話(でんわ)してください。",1]);
P.push(["as well as ~","不仅…而且","〜と同様(どうよう)に","He speaks French as well as English.","彼(かれ)は英語(えいご)だけでなくフランス語(ご)も話(はな)す。",1]);
P.push(["as ~ as ...","和…一样","…と同(おな)じくらい〜","He is as tall as his father.","彼(かれ)は父親(ちちおや)と同(おな)じくらい背(せ)が高(たか)い。",2]);
P.push(["not as ~ as ...","不如…","…ほど〜ではない","This book is not as difficult as that one.","この本(ほん)はあの本(ほん)ほど難(むずか)しくない。",2]);
P.push(["both A and B","A和B都","AもBも両方(りょうほう)とも","Both my sister and I like music.","姉(あね)も私(わたし)も音楽(おんがく)が好(す)きだ。",2]);
P.push(["either A or B","A或B","AかBのどちらか","You can choose either tea or coffee.","紅茶(こうちゃ)かコーヒーのどちらかを選(えら)べます。",1]);
P.push(["not only A but also B","不仅A而且B","AだけでなくBも","He is not only kind but also honest.","彼(かれ)は親切(しんせつ)なだけでなく正直(しょうじき)でもある。",1]);
P.push(["so ~ that ...","如此…以至于","とても〜なので…","He was so tired that he fell asleep.","彼(かれ)はとても疲(つか)れていたので眠(ねむ)ってしまった。",1]);
P.push(["too ~ to ...","太…而不能","…するには〜すぎる","This box is too heavy to carry.","この箱(はこ)は重(おも)すぎて運(はこ)べない。",1]);
P.push(["~ enough to ...","足够…能","…するのに十分(じゅうぶん)〜","She is old enough to drive.","彼女(かのじょ)は運転(うんてん)できる年齢(ねんれい)だ。",1]);
P.push(["It is ~ for A to ...","对A来说…是…","Aが…するのは〜だ","It is difficult for me to get up early.","早起(はやお)きするのは私(わたし)には難(むずか)しい。",1]);
P.push(["It takes ~ to ...","做…花费…","…するのに〜かかる","It takes ten minutes to walk there.","そこまで歩(ある)いて十分(じゅっぷん)かかる。",2]);
P.push(["There is / There are ~","有…","〜がある","There is a library near my house.","家(いえ)の近(ちか)くに図書館(としょかん)がある。",3]);
P.push(["used to ~","过去常常","以前(いぜん)はよく〜した","I used to play the piano.","私(わたし)は以前(いぜん)よくピアノを弾(ひ)いた。",1]);
P.push(["would like to ~","想要…","〜したい","I would like to visit Kyoto.","私(わたし)は京都(きょうと)を訪(おとず)れたい。",2]);
P.push(["had better ~","最好…","〜したほうがよい","You had better see a doctor.","医者(いしゃ)に診(み)てもらったほうがよい。",1]);
P.push(["have to ~","必须…","〜しなければならない","I have to finish this today.","私(わたし)は今日中(きょうじゅう)にこれを終(お)えなければならない。",3]);
P.push(["don't have to ~","不必…","〜する必要(ひつよう)はない","You don't have to come early.","早(はや)く来(く)る必要(ひつよう)はありません。",2]);
P.push(["must not ~","不可以…","〜してはいけない","You must not touch it.","それに触(さわ)ってはいけない。",2]);
P.push(["How about ~ing?","…怎么样？","〜するのはどうですか","How about going to the movies?","映画(えいが)を見(み)に行(い)くのはどうですか。",2]);
P.push(["Why don't you ~?","你何不…？","〜したらどうですか","Why don't you ask your teacher?","先生(せんせい)に聞(き)いてみたらどうですか。",2]);
P.push(["Shall I ~?","要我…吗？","〜しましょうか","Shall I open the window?","窓(まど)を開(あ)けましょうか。",2]);
P.push(["Would you like ~?","您要…吗？","〜はいかがですか","Would you like some tea?","お茶(ちゃ)はいかがですか。",2]);
P.push(["Could you ~?","能请您…吗？","〜していただけますか","Could you say that again?","もう一度(いちど)言(い)っていただけますか。",2]);
P.push(["May I ~?","我可以…吗？","〜してもいいですか","May I use your pen?","ペンを使(つか)ってもいいですか。",3]);
P.push(["What do you think of ~?","你觉得…怎么样？","〜をどう思(おも)いますか","What do you think of this plan?","この計画(けいかく)をどう思(おも)いますか。",2]);
P.push(["one of the ~est","最…之一","最(もっと)も〜なものの一(ひと)つ","This is one of the oldest temples.","これは最(もっと)も古(ふる)い寺(てら)の一(ひと)つだ。",1]);
P.push(["the more ~, the more ...","越…越…","〜すればするほど…","The more you practice, the better you get.","練習(れんしゅう)すればするほど上手(じょうず)になる。",1]);
P.push(["more and more ~","越来越…","ますます〜","More and more people use bikes.","ますます多(おお)くの人(ひと)が自転車(じてんしゃ)を使(つか)う。",1]);
P.push(["according to ~","根据…","〜によれば","According to the news, it will rain.","ニュースによれば、雨(あめ)が降(ふ)るそうだ。",1]);
P.push(["thanks to ~","多亏…","〜のおかげで","Thanks to your help, I finished it.","あなたの助(たす)けのおかげで終(お)えられた。",1]);
P.push(["because of ~","因为…","〜のために","The game was canceled because of rain.","雨(あめ)のため試合(しあい)は中止(ちゅうし)になった。",2]);
P.push(["instead of ~","代替…","〜の代(か)わりに","I drank tea instead of coffee.","コーヒーの代(か)わりに紅茶(こうちゃ)を飲(の)んだ。",1]);
P.push(["such as ~","例如…","〜のような","I like fruit such as apples.","私(わたし)はりんごのような果物(くだもの)が好(す)きだ。",1]);
P.push(["more than ~","超过…","〜より多(おお)く","More than fifty people came.","五十人(ごじゅうにん)以上(いじょう)が来(き)た。",2]);
P.push(["most of ~","大部分的…","〜のほとんど","Most of the students agreed.","生徒(せいと)のほとんどが賛成(さんせい)した。",2]);
P.push(["a kind of ~","一种…","一種(いっしゅ)の〜","It is a kind of Japanese food.","それは日本料理(にほんりょうり)の一種(いっしゅ)だ。",1]);
P.push(["be going to ~","打算…","〜するつもりだ","I am going to study abroad.","私(わたし)は留学(りゅうがく)するつもりだ。",3]);
P.push(["want A to ~","想让A做…","Aに〜してほしい","I want you to come with me.","あなたに一緒(いっしょ)に来(き)てほしい。",2]);
P.push(["tell A to ~","叫A做…","Aに〜するように言(い)う","She told me to wait here.","彼女(かのじょ)は私(わたし)にここで待(ま)つように言(い)った。",2]);
P.push(["ask A to ~","请求A做…","Aに〜するよう頼(たの)む","I asked him to help me.","私(わたし)は彼(かれ)に手伝(てつだ)ってくれるよう頼(たの)んだ。",2]);
P.push(["help A ~","帮助A做…","Aが〜するのを手伝(てつだ)う","He helped me carry the box.","彼(かれ)は私(わたし)が箱(はこ)を運(はこ)ぶのを手伝(てつだ)ってくれた。",2]);
P.push(["let A ~","让A做…","Aに〜させる","Let me try once more.","もう一度(いちど)やらせてください。",2]);
P.push(["make A ~","使A…","Aを〜にする","The news made me happy.","その知(し)らせは私(わたし)を幸(しあわ)せにした。",2]);
P.push(["stop ~ing","停止做…","〜するのをやめる","He stopped talking suddenly.","彼(かれ)は突然(とつぜん)話(はな)すのをやめた。",2]);
P.push(["finish ~ing","做完…","〜し終(お)える","I finished reading the book.","私(わたし)はその本(ほん)を読(よ)み終(お)えた。",2]);
P.push(["enjoy ~ing","享受做…","〜するのを楽(たの)しむ","We enjoyed talking with them.","私(わたし)たちは彼(かれ)らと話(はな)すのを楽(たの)しんだ。",2]);
P.push(["be busy ~ing","忙于做…","〜するのに忙(いそが)しい","She is busy preparing for the trip.","彼女(かのじょ)は旅行(りょこう)の準備(じゅんび)で忙(いそが)しい。",1]);
P.push(["How long ~?","多久？","どのくらいの間(あいだ)〜","How long have you lived here?","どのくらいここに住(す)んでいますか。",2]);
P.push(["How many ~?","多少个？","いくつの〜","How many books do you have?","本(ほん)を何冊(なんさつ)持(も)っていますか。",3]);
P.push(["How often ~?","多久一次？","どのくらいの頻度(ひんど)で〜","How often do you play tennis?","どのくらいテニスをしますか。",2]);
P.push(["Have you ever ~?","你曾经…吗？","〜したことがありますか","Have you ever been to Hokkaido?","北海道(ほっかいどう)へ行(い)ったことがありますか。",2]);
P.push(["have been to ~","去过…","〜へ行(い)ったことがある","I have been to Kyoto twice.","私(わたし)は京都(きょうと)へ二度(にど)行(い)ったことがある。",2]);
P.push(["have been ~ing","一直在做…","ずっと〜し続(つづ)けている","I have been studying for two hours.","私(わたし)は二時間(にじかん)ずっと勉強(べんきょう)している。",1]);
P.push(["It is said that ~","据说…","〜と言(い)われている","It is said that he is a genius.","彼(かれ)は天才(てんさい)だと言(い)われている。",1]);
P.push(["the way to ~","去…的路","〜への行(い)き方(かた)","Could you tell me the way to the museum?","博物館(はくぶつかん)への行(い)き方(かた)を教(おし)えていただけますか。",2]);
P.push(["make friends with ~","与…交朋友","〜と友(とも)だちになる","I made friends with a girl from India.","私(わたし)はインド出身(しゅっしん)の女(おんな)の子(こ)と友(とも)だちになった。",1]);
P.push(["take a look at ~","看一看…","〜をちょっと見(み)る","Take a look at this graph.","このグラフをちょっと見(み)てください。",1]);
P.push(["come up with ~","想出…","〜を思(おも)いつく","She came up with a good idea.","彼女(かのじょ)はよい考(かんが)えを思(おも)いついた。",1]);
P.push(["put off ~","推迟…","〜を延期(えんき)する","They put off the meeting.","彼(かれ)らは会議(かいぎ)を延期(えんき)した。",1]);
P.push(["run out of ~","用完…","〜を切(き)らす","We ran out of paper.","紙(かみ)を切(き)らしてしまった。",1]);
P.push(["be tired of ~","厌倦…","〜にあきている","I am tired of doing the same thing.","同(おな)じことをするのにあきた。",1]);
P.push(["be used to ~ing","习惯于…","〜することに慣(な)れている","He is used to speaking English.","彼(かれ)は英語(えいご)を話(はな)すのに慣(な)れている。",1]);
P.push(["give A a hand","帮A一把","Aに手(て)を貸(か)す","Could you give me a hand?","手(て)を貸(か)していただけますか。",1]);
P.push(["keep ~ing","持续做…","〜し続(つづ)ける","He kept running for an hour.","彼(かれ)は一時間(いちじかん)走(はし)り続(つづ)けた。",2]);
P.push(["stop A from ~ing","阻止A做…","Aが〜するのを妨(さまた)げる","The rain stopped us from going out.","雨(あめ)のせいで外出(がいしゅつ)できなかった。",1]);
P.push(["be filled with joy","充满喜悦","喜(よろこ)びでいっぱいだ","Her heart was filled with joy.","彼女(かのじょ)の心(こころ)は喜(よろこ)びでいっぱいだった。",1]);
P.push(["for a while","一会儿","しばらくの間(あいだ)","Please wait here for a while.","しばらくここでお待(ま)ちください。",1]);
P.push(["little by little","一点一点地","少(すこ)しずつ","He is getting better little by little.","彼(かれ)は少(すこ)しずつよくなっている。",1]);
P.push(["one another","互相","お互(たが)いに","We should help one another.","私(わたし)たちはお互(たが)いに助(たす)け合(あ)うべきだ。",1]);
P.push(["on the other hand","另一方面","一方(いっぽう)で","On the other hand, it costs a lot.","一方(いっぽう)で、費用(ひよう)がかなりかかる。",1]);
P.push(["in this way","以这种方式","このようにして","In this way, we saved energy.","このようにして、私(わたし)たちはエネルギーを節約(せつやく)した。",1]);
P.push(["as a result","结果","その結果(けっか)","As a result, the number decreased.","その結果(けっか)、数(かず)が減(へ)った。",1]);
P.push(["these days","最近","最近(さいきん)では","These days many people work at home.","最近(さいきん)では在宅(ざいたく)で働(はたら)く人(ひと)が多(おお)い。",1]);
P.push(["from now on","从今以后","これからは","From now on, I will study every day.","これからは毎日(まいにち)勉強(べんきょう)します。",1]);
