S.push(["May I ask you a question?","我可以问个问题吗？","質問(しつもん)してもいいですか。",3]);
S.push(["Could you say that again, please?","能请您再说一遍吗？","もう一度(いちど)言(い)っていただけますか。",3]);
S.push(["How do you spell it?","这个怎么拼？","つづりを教(おし)えてください。",3]);
S.push(["What does this word mean?","这个单词是什么意思？","この単語(たんご)はどういう意味(いみ)ですか。",3]);
S.push(["I'm sorry, I don't understand.","抱歉，我不明白。","すみません、わかりません。",3]);
S.push(["Please speak more slowly.","请说慢一点。","もっとゆっくり話(はな)してください。",3]);
S.push(["Let me try once more.","让我再试一次。","もう一度(いちど)やらせてください。",2]);
S.push(["May I go to the restroom?","我可以去洗手间吗？","お手洗(てあら)いに行(い)ってもいいですか。",3]);
S.push(["I forgot to bring my textbook.","我忘带课本了。","教科書(きょうかしょ)を持(も)ってくるのを忘(わす)れました。",2]);
S.push(["Can I borrow your eraser?","能借我橡皮吗？","消(け)しゴムを借(か)りてもいいですか。",3]);
S.push(["We are going to have a test tomorrow.","明天我们有考试。","明日(あした)テストがあります。",3]);
S.push(["Please hand in your report by Friday.","请在周五前交报告。","金曜日(きんようび)までにレポートを提出(ていしゅつ)してください。",2]);
S.push(["Excuse me, could you tell me the way to the station?","打扰一下，能告诉我去车站怎么走吗？","すみません、駅(えき)への行(い)き方(かた)を教(おし)えていただけますか。",3]);
S.push(["Go straight and turn right at the second corner.","直走，在第二个路口右转。","まっすぐ行(い)って、二(ふた)つ目(め)の角(かど)を右(みぎ)に曲(ま)がってください。",2]);
S.push(["It takes about ten minutes on foot.","走路大约十分钟。","徒歩(とほ)で約(やく)十分(じゅっぷん)かかります。",2]);
S.push(["You can't miss it.","你不会错过的。","すぐにわかりますよ。",1]);
S.push(["Which bus goes to the museum?","哪路公交去博物馆？","どのバスが博物館(はくぶつかん)へ行(い)きますか。",2]);
S.push(["How much is this?","这个多少钱？","これはいくらですか。",3]);
S.push(["I'll take this one.","我要这个。","これをいただきます。",3]);
S.push(["Do you have a smaller size?","有小一点的尺码吗？","もっと小(ちい)さいサイズはありますか。",2]);
S.push(["I'm just looking, thank you.","我只是看看，谢谢。","見(み)ているだけです、ありがとう。",2]);
S.push(["Here you are.","给你。","はい、どうぞ。",3]);
S.push(["Hello. This is Ken speaking.","你好，我是健。","もしもし、健(けん)です。",3]);
S.push(["May I speak to Mr. Brown?","我可以和布朗先生通话吗？","ブラウンさんをお願(ねが)いできますか。",2]);
S.push(["I'm sorry, he is out now.","抱歉，他现在不在。","すみません、彼(かれ)は今(いま)外出中(がいしゅつちゅう)です。",2]);
S.push(["Can I leave a message?","我可以留言吗？","伝言(でんごん)をお願(ねが)いできますか。",2]);
S.push(["I'll call you back later.","我稍后回电给你。","あとでかけ直(なお)します。",2]);
S.push(["Shall I help you with your bag?","要我帮你拿包吗？","かばんをお持(も)ちしましょうか。",2]);
S.push(["Would you like something to drink?","要喝点什么吗？","何(なに)か飲(の)み物(もの)はいかがですか。",2]);
S.push(["Thank you very much for your help.","非常感谢你的帮助。","助(たす)けてくださって本当(ほんとう)にありがとうございます。",3]);
S.push(["You're welcome.","不客气。","どういたしまして。",3]);
S.push(["I'm sorry to hear that.","听到这个我很难过。","それはお気(き)の毒(どく)に。",2]);
S.push(["Nice to meet you. My name is Lin.","很高兴认识你，我叫林。","はじめまして。林(りん)といいます。",3]);
S.push(["I'm from China, but I live in Japan now.","我来自中国，现在住在日本。","中国(ちゅうごく)出身(しゅっしん)ですが、今(いま)は日本(にほん)に住(す)んでいます。",3]);
S.push(["I'm a third-year student at this school.","我是这所学校三年级的学生。","私(わたし)はこの学校(がっこう)の三年生(さんねんせい)です。",3]);
S.push(["I belong to the tennis club.","我参加网球社。","私(わたし)はテニス部(ぶ)に所属(しょぞく)しています。",3]);
S.push(["My favorite subject is English.","我最喜欢的科目是英语。","私(わたし)の好(す)きな教科(きょうか)は英語(えいご)です。",3]);
S.push(["I like reading books in my free time.","我空闲时喜欢读书。","ひまなときは本(ほん)を読(よ)むのが好(す)きです。",3]);
S.push(["In the future, I want to work abroad.","将来我想在国外工作。","将来(しょうらい)は海外(かいがい)で働(はたら)きたいです。",2]);
S.push(["Today I'd like to talk about the environment.","今天我想谈谈环境。","今日(きょう)は環境(かんきょう)についてお話(はな)ししたいと思(おも)います。",2]);
S.push(["Thank you for listening.","谢谢聆听。","ご清聴(せいちょう)ありがとうございました。",2]);
S.push(["I have three reasons for this.","我有三个理由。","理由(りゆう)は三(みっ)つあります。",2]);
S.push(["First, it is good for our health.","第一，这对健康有益。","第一(だいいち)に、それは健康(けんこう)によいです。",2]);
S.push(["Second, it does not cost much money.","第二，它花不了多少钱。","第二(だいに)に、あまりお金(かね)がかかりません。",2]);
S.push(["Finally, it is easy for everyone to start.","最后，任何人都容易开始。","最後(さいご)に、誰(だれ)でも簡単(かんたん)に始(はじ)められます。",2]);
S.push(["I think that we should protect nature.","我认为我们应该保护自然。","私(わたし)たちは自然(しぜん)を守(まも)るべきだと思(おも)います。",2]);
S.push(["I agree with this idea for two reasons.","我赞成这个想法，有两个理由。","二(ふた)つの理由(りゆう)でこの考(かんが)えに賛成(さんせい)です。",1]);
S.push(["In my opinion, reading is very important.","在我看来，阅读非常重要。","私(わたし)の意見(いけん)では、読書(どくしょ)はとても大切(たいせつ)です。",1]);
S.push(["For example, we can start by saving water.","例如，我们可以从节约用水开始。","たとえば、水(みず)を節約(せつやく)することから始(はじ)められます。",2]);
S.push(["For these reasons, I believe it is a good idea.","基于这些理由，我相信这是个好主意。","これらの理由(りゆう)から、よい考(かんが)えだと思(おも)います。",1]);
S.push(["On the other hand, some people don't agree.","另一方面，有些人不赞成。","一方(いっぽう)で、賛成(さんせい)しない人(ひと)もいます。",1]);
S.push(["That is why I want to be a teacher.","这就是我想当老师的原因。","だから私(わたし)は先生(せんせい)になりたいのです。",1]);
S.push(["The more we learn, the more we want to know.","学得越多，就越想知道更多。","学(まな)べば学(まな)ぶほど、もっと知(し)りたくなります。",1]);
S.push(["It is important for us to help each other.","互相帮助对我们来说很重要。","お互(たが)いに助(たす)け合(あ)うことが私(わたし)たちには大切(たいせつ)です。",1]);
S.push(["I was so happy that I couldn't say anything.","我高兴得说不出话来。","うれしすぎて何(なに)も言(い)えませんでした。",1]);
S.push(["This book is too difficult for me to read.","这本书对我来说太难读了。","この本(ほん)は難(むずか)しすぎて私(わたし)には読(よ)めません。",1]);
S.push(["He is one of the most famous singers in Japan.","他是日本最有名的歌手之一。","彼(かれ)は日本(にほん)で最(もっと)も有名(ゆうめい)な歌手(かしゅ)の一人(ひとり)です。",1]);
S.push(["The number of foreign visitors is increasing.","外国游客的数量在增加。","外国人(がいこくじん)訪問者(ほうもんしゃ)の数(かず)が増(ふ)えています。",1]);
S.push(["According to the graph, about half of them agreed.","根据图表，大约一半的人赞成。","グラフによると、約半数(やくはんすう)が賛成(さんせい)しました。",1]);
S.push(["This temple was built about 400 years ago.","这座寺庙建于大约400年前。","この寺(てら)は約(やく)四百年前(よんひゃくねんまえ)に建(た)てられました。",1]);
S.push(["English is spoken by many people around the world.","世界上很多人说英语。","英語(えいご)は世界中(せかいじゅう)の多(おお)くの人(ひと)に話(はな)されています。",2]);
S.push(["I have lived in this town since I was five.","我从五岁起就住在这个镇上。","私(わたし)は五歳(ごさい)のときからこの町(まち)に住(す)んでいます。",2]);
S.push(["Have you ever thought about your future?","你想过自己的将来吗？","将来(しょうらい)について考(かんが)えたことがありますか。",2]);
S.push(["If I were you, I would tell the truth.","如果我是你，我会说实话。","私(わたし)があなたなら、本当(ほんとう)のことを言(い)うでしょう。",1]);
S.push(["I wish I could speak English like you.","我希望能像你一样说英语。","あなたのように英語(えいご)が話(はな)せたらいいのに。",1]);
S.push(["Do you know where he is from?","你知道他来自哪里吗？","彼(かれ)がどこの出身(しゅっしん)か知(し)っていますか。",1]);
S.push(["Please tell me what you want to do.","请告诉我你想做什么。","何(なに)がしたいのか教(おし)えてください。",1]);
S.push(["The girl playing the piano is my sister.","正在弹钢琴的女孩是我妹妹。","ピアノを弾(ひ)いている女(おんな)の子(こ)は私(わたし)の妹(いもうと)です。",1]);
S.push(["This is the book which I bought yesterday.","这是我昨天买的书。","これは私(わたし)が昨日(きのう)買(か)った本(ほん)です。",1]);
S.push(["I know a boy whose father is a doctor.","我认识一个父亲是医生的男孩。","私(わたし)は父親(ちちおや)が医者(いしゃ)である男(おとこ)の子(こ)を知(し)っています。",1]);
